name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 0 * * *' # every night at midnight
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          expire-in: 1days 
