name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '42 * * *' # every one hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          expire-in: 7days # Set this to 0 to delete all artifacts
